#!/usr/bin/with-contenv bash

# unset unraid specific ENV to avoid crashing
unset HOST_OS

cd /app/hydra2 || exit

IFS=" " read -r -a RUN_ARRAY <<< "$RUN_OPTS"

exec \
	s6-setuidgid abc /usr/bin/python nzbhydra2wrapper.py \
	--nobrowser --datafolder /config "${RUN_ARRAY[@]}"
